### ISSUE TITLE
9.5 Competency checklist

### ISSUE THREAD

**Issue by harrison-symes** [phase-0/phase-0#1575]
# 9.5 Competency checklist

This is a checklist of the core competencies you need for bootcamp :seedling:

## Command line
I can:
- [x] navigate
- [x] create files
- [x] rename files
- [x] move files

## Git
I can:
- [x] clone
- [x] stage & push
- [x] pull
- [x] branch
- [x] handle pull requests
- [x] make good commit messages
- [x] make small frequent commits
- [x] view my git log

## Design
I can:
- [x] create wireframes
- [x] 'boxify' my wireframes ready for HTML & CSS creation

## HTML
I can:
- [x] create elements
- [x] use tag attributes
- [x] use semantic HTML
- [x] create a valid HTML page structure
- [x] perfectly indent my HTML
- [x] create HTML from wireframes
- [x] use HTML **only** for content, not styling
- [x] abstain from inline styling
- [ ] use Content Delivery Networks (CDNs)

## CSS
I can:
- [x] link CSS file to HTML file
- [x] use element selectors
- [x] use class selectors
- [x] use good reusable class names
- [x] use child and parent selectors
- [x] use CSS specificity
- [x] use the cascading nature of CSS
- [x] apply colors
- [x] apply font styling
- [x] normalise CSS across browsers
- [x] use Google Dev Tools to inspect and test CSS
- [x] handle images with CSS
- [x] position elements with
  - [x] fixed position
  - [x] absolute position
  - [x] relative position
  - [x] static position
- [x] use flexbox to position elements
- [x] use the box model to position and style elements
- [x] use media queries
- [x] use mobile first styling
- [x] use a grid framework to create a responsive page

## DOM
I can:
- [x] inspect the DOM in Chrome DevTools

## JS
I can:
- [x] link JS file to HTML file
- [x] use all the JS datatypes
- [x] declare variables
- [x] manipulate strings
- [x] manipulate arrays
- [x] manipulate objects
- [x] use prompts and alerts
- [x] use comments in my code
- [x] use if/else statements
- [x] use switch statements
- [ ] use basic regular expressions
- [ ] use 'truthy' and 'falsy' values
- [ ] use vanilla JS to manipulate the DOM
- [ ] use jQuery to manipulate the DOM
- [ ] use console.log
- [ ] perfectly indent my JS
- [ ] use and understand scope
- [ ] declare functions
- [ ] explain the difference between arguments and parameters
- [ ] return things from functions
- [ ] use `while`/`do` loops
- [ ] use `for` loops
- [ ] use `map`
- [ ] use `reduce`
- [ ] use `filter`
- [ ] give my functions and variables good descriptive names
- [ ] create single responsibility functions

## Problem Solving
I can:
- [ ] pseudocode
- [ ] try some code
- [ ] isolate the bug
- [ ] debug -
  - [ ] talk to my rubber ducky
  - [ ] read the error messages
  - [ ] console.log
  - [ ] google
- [ ] ask my other students
- [ ] ask a coach
- [ ] reflect and learn from my experience
- [ ] recognise when I need to ask for help

## Learning
I can:
- [ ] identify how I learn best
- [ ] optimise my learning
- [ ] prioritise process over product

## Habits
I have developed habits of:
- [ ] reflecting
- [ ] tidying
- [ ] playing
- [ ] perservering
- [ ] exploring
- [ ] communication
- [ ] equinimity
- [ ] honing
- [ ] sharing

## Human Skills
I can increasingly:
- [ ] meditate (even if just a couple of minutes)
- [ ] observe my patterns of thought
- [ ] hold attention
- [ ] apply mindfulness to my interactions other students and Dev Academy
- [ ] journal
- [ ] body scan
- [ ] stop identifying with my emotions
- [ ] identify my values
- [ ] use listening and looping
- [ ] use empathic listening
- [ ] communicate openly and honestly
- [ ] give valuable, kind and honest feedback
- [ ] gracefully recieve feedback
- [ ] hold integrity
- [ ] hold kindness
- [ ] hold effort
