### ISSUE TITLE
9.5 Competency checklist

### ISSUE THREAD

**Issue by harrison-symes** [phase-0/phase-0#488]
# 9.5 Competency checklist

This is a checklist of the core competencies you need for bootcamp :seedling:

## Command line
I can:
- [x] navigate
- [x] create files
- [x] rename files
- [x] move files

## Git
I can:
- [x] clone
- [x] stage & push
- [x] pull
- [x] branch
- [x] handle pull requests
- [x] make good commit messages
- [x] make small frequent commits
- [x] view my git log

## Design
I can:
- [x] create wireframes
- [x] 'boxify' my wireframes ready for HTML & CSS creation

## HTML
I can:
- [x] create elements
- [x] use tag attributes
- [x] use semantic HTML
- [x] create a valid HTML page structure
- [x] perfectly indent my HTML
- [x] create HTML from wireframes
- [x] use HTML **only** for content, not styling
- [x] abstain from inline styling
- [x] use Content Delivery Networks (CDNs)

## CSS
I can:
- [x] link CSS file to HTML file
- [x] use element selectors
- [x] use class selectors
- [x] use good reusable class names
- [x] use child and parent selectors
- [x] use CSS specificity
- [x] use the cascading nature of CSS
- [x] apply colors
- [x] apply font styling
- [x] normalise CSS across browsers
- [x] use Google Dev Tools to inspect and test CSS
- [x] handle images with CSS
- [x] position elements with
  - [x] fixed position
  - [x] absolute position
  - [x] relative position
  - [x] static position
- [x] use flexbox to position elements
- [x] use the box model to position and style elements
- [x] use media queries
- [x] use mobile first styling
- [x] use a grid framework to create a responsive page

## DOM
I can:
- [x] inspect the DOM in Chrome DevTools

## JS
I can:
- [x] link JS file to HTML file
- [x] use all the JS datatypes
- [x] declare variables
- [x] manipulate strings
- [x] manipulate arrays
- [x] manipulate objects
- [x] use prompts and alerts
- [x] use comments in my code
- [x] use if/else statements
- [x] use switch statements
- [x] use basic regular expressions
- [x] use 'truthy' and 'falsy' values
- [x] use vanilla JS to manipulate the DOM
- [x] use jQuery to manipulate the DOM
- [x] use console.log
- [x] perfectly indent my JS
- [x] use and understand scope
- [x] declare functions
- [x] explain the difference between arguments and parameters
- [x] return things from functions
- [x] use `while`/`do` loops
- [x] use `for` loops
- [x] use `map`
- [x] use `reduce`
- [x] use `filter`
- [x] give my functions and variables good descriptive names
- [x] create single responsibility functions

## Problem Solving
I can:
- [x] pseudocode
- [x] try some code
- [x] isolate the bug
- [x] debug -
  - [x] talk to my rubber ducky
  - [x] read the error messages
  - [x] console.log
  - [x] google
- [x] ask my cohort
- [x] ask a coach
- [x] reflect and learn from my experience
- [x] recognise when I need to ask for help

## Learning
I can:
- [x] identify how I learn best
- [x] optimise my learning
- [x] prioritise process over product

## Habits
I have developed habits of:
- [x] reflecting
- [x] tidying
- [x] playing
- [x] perservering
- [x] exploring
- [x] communication
- [x] equinimity
- [x] honing
- [x] sharing

## Human Skills
I can increasingly:
- [x] meditate (even if just a couple of minutes)
- [x] observe my patterns of thought
- [x] hold attention
- [x] apply mindfulness to my interactions with my cohort and Dev Academy
- [x] journal
- [x] body scan
- [x] stop identifying with my emotions
- [x] identify my values
- [x] use listening and looping
- [x] use empathic listening
- [x] communicate openly and honestly
- [x] give valuable, kind and honest feedback
- [x] gracefully recieve feedback
- [x] hold integrity
- [x] hold kindness
- [x] hold effort
